DROP ROLE lmsadmin;
CREATE USER lmsdadmin WITH PASSWORD 'sup3rs3cr3t';

DROP DATABASE IF EXISTS lms;
CREATE DATABASE lms;
GRANT ALL PRIVILEGES ON DATABASE lms TO lmsadmin;

DROP SCHEMA IF EXISTS development;
CREATE SCHEMA IF NOT EXISTS development;
ALTER SCHEMA development OWNER TO lmsadmin;
